@Host = http://127.0.0.1:10800

GET {{Host}}/cats HTTP/1.1

###

POST {{Host}}/cats HTTP/1.1
Content-Type: application/json

{
    "name": "Lucky1"
}

###

PUT {{Host}}/cats/2 HTTP/1.1
Content-Type: application/json

{
    "name": "LuckyOne"
}

###

DELETE {{Host}}/cats/55ba0f92-fe3e-42f6-b557-f86a99b8fd70 HTTP/1.1
Content-Type: application/json
